### PR TITLE
fix: Use sessionStorage for refresh messages (#56)

### LINKED ISSUE #56: Page refresh message shown on first visit
In Firefox 110.0, the first time you enter CMF, it shows a page refresh message on the button, not a first time welcome message.

### PR DESCRIPTION
**Pull request by Cthulhu2**
closes #56

### CODE REVIEW

File: pages/index.js [hunk 1]
```diff
@@ -40,17 +40,14 @@ function Index({ trackId, backSideContent, latestId }) {
   }, [enterKey]);
 
   React.useEffect(() => {
-    if (localStorage.getItem("refresh") === "true"){
-      localStorage.setItem("refresh", false)
+    if (sessionStorage.getItem("refresh") === "true"){
```
Comment (orhun) [inline pages/index.js:43]: Shouldn't we set `refresh` to `false` after this line?

```js
sessionStorage.setItem("refresh", false);
```

Comment (Cthulhu2) [reply pages/index.js:43]: No. Just set once per session, without `onbeforeunload`, and show refresh-messages always except the first loading.

**Review by orhun — APPROVED** [review]
